name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: rm -f .env && mv .env.ci .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php fluentkit key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Start MySql
      run: sudo /etc/init.d/mysql start
    - name: Create Database
      run: mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS ci;'
    - name: Install Application
      run: php fluentkit install --ci --app-name="Testing" --app-domain="http://localhost" --email="noreply@fluentkit.io" --first-name="Fluent" --last-name="Kit" --password="FluentkitKitIsAwesome!"
    - name: Optimise Application
      run: php fluentkit config:cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php fluentkit test
    - name: Upload Error Log
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: error.log
        path: storage/logs/fluentkit.log
